workspace:
  base: /go
  path: src/github.com/skuid/dimsum
pipeline:
  build:
    image: golang:1.13-alpine
    commands:
      - go build -v
  publish:
    image: plugins/docker
    secrets: [docker_username, docker_password]
    registry: quay.io
    repo: quay.io/skuid/dimsum
    tags:
      - ${DRONE_TAG}
    when:
      event: tag
